"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.toggleBoolean = exports.randomBoolean = exports.randomInteger = exports.isObjectEmpty = exports.isArrayEmpty = exports.capitalize = exports.wait = exports.isWeekday = exports.reverse = exports.isEven = exports.Greeter = void 0;
var Greeter = function (name) { return "Hello ".concat(name); };
exports.Greeter = Greeter;
var isEven = function (n) { return n % 2 === 0; };
exports.isEven = isEven;
var reverse = function (s) { return s.split('').reverse().join(''); };
exports.reverse = reverse;
var isWeekday = function (d) { return d.getDay() % 6 !== 0; };
exports.isWeekday = isWeekday;
var wait = function (ms) { return new Promise(function (resolve) { return setTimeout(resolve, ms); }); };
exports.wait = wait;
var capitalize = function (s) { return s.charAt(0).toUpperCase() + s.slice(1); };
exports.capitalize = capitalize;
var isArrayEmpty = function (arr) { return Array.isArray(arr) && !arr.length; };
exports.isArrayEmpty = isArrayEmpty;
var isObjectEmpty = function (obj) { return obj && Object.keys(obj).length === 0; };
exports.isObjectEmpty = isObjectEmpty;
var randomInteger = function (min, max) { return Math.floor(Math.random() * (max - min + 1)) + min; };
exports.randomInteger = randomInteger;
var randomBoolean = function () { return Math.random() >= 0.5; };
exports.randomBoolean = randomBoolean;
var toggleBoolean = function (val) { return (val = !val); };
exports.toggleBoolean = toggleBoolean;
